In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("records_final_series_ODI.csv")

In [3]:
df.head()

,Player,Country,% Team Runs,Mat,Inns,NO,50s,100s,0s,HS,Runs,S/R,Avg,Ca,St,Series_Code,H/A,Decade_Index
0,Zulquarnain,England,43.16%,1,1,0,1,0,0,82,82,68.91,82,0,0,193,Away,0
1,Zulquarnain,Australia,31.41%,1,1,0,1,0,0,60,60,58.25,60,0,0,193,Home,0
2,Zulquarnain,Australia,21.47%,1,1,0,0,0,0,41,41,80.39,41,1,0,193,Home,0
3,Zulqarnain Haider,Australia,14.14%,1,1,0,0,0,0,27,27,55.1,27,1,0,193,Home,0
4,Zulfiqar Babar,England,12.63%,1,1,0,0,0,0,24,24,77.42,24,2,1,193,Away,0